### ISSUE TITLE
Disable excluded_clients

### ISSUE THREAD

**Issue by PezCoder** [seatgeek/sixpack-php#18]
1. I didn't find any documentation regarding excluded_clients, how can I disable that temporarily to test sixpack locally. 
2. Also is http://localhost:5001/experiments.json the only dashboard. I remember in the previous version you use to have a interactive dashboard with alot of other options.

**Comment by PezCoder** [comment]
@zackkitzmiller Can u help ?

**Comment by josegonzalez** [comment]
1. The excluded clients are managed by the traffic distribution afforded to each test. Instead of trying to use sixpack to disable the test locally, just bail in your php code and set the default alternative.
2. You need to run sixpack-web for the dashboard.
