### ISSUE TITLE
So does it evenly cycle?

### ISSUE THREAD

**Issue by MACscr** [seatgeek/sixpack-php#22]
I need to try to have as close as possible the same amount of viewers to each content so that I can properly chart the data. If I have 100 visitors, it would be ideal if 50 saw Content A and 50 saw Content B. Does your solution do this out of the box?

I tried messing with the sample, yet even after deleting the cookie and refreshing the page, I still kept getting 'blue'.

**Comment by zackkitzmiller** [comment]
It sounds to me like the client isn't correctly hitting the server and always returning the control option. Can you confirm that the server is reachable from the client?

**Comment by MACscr** [comment]
What server? I'm I ignorant of further requirements that are not in the readme?

- Mark

**Comment by MACscr** [comment]
Oops, I am. Please disregard and delete or close this issue. lol 

- Mark

**Comment by zackkitzmiller** [comment]
From the Readme: 

PHP client library for SeatGeak's [Sixpack](https://github.com/seatgeek/sixpack) ab testing framework.
